# Generated by Django 3.2.8 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.CharField(default='01', max_length=2, verbose_name='position grade'),
        ),
        migrations.AlterField(
            model_name='position',
            name='series',
            field=models.CharField(default='A', max_length=1, verbose_name='position series'),
        ),
    ]
