# Generated by Django 3.0.7 on 2020-06-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[], default='01', max_length=2, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='data', verbose_name='attach'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['basedata', 'organ', 'auth']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='doc', verbose_name='attach'),
        ),
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(choices=[], default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('0', 'draft'), ('1', 'published')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tp',
            field=models.CharField(choices=[('00', 'SYSTEM MANUAL'), ('10', 'BUSINESS DOC')], default='10', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[], default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=[], default='1', max_length=2, verbose_name='edu type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[], default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[], default='CN', max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=[], default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[], default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health',
            field=models.CharField(blank=True, choices=[], default='1', max_length=2, null=True, verbose_name='health'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='literacy',
            field=models.CharField(blank=True, choices=[], default='10', max_length=2, null=True, verbose_name='literacy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, choices=[], default='99', max_length=2, null=True, verbose_name='major type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital',
            field=models.CharField(blank=True, choices=[], default='10', max_length=2, null=True, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, choices=[], default='01', max_length=2, null=True, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, choices=[], default='13', max_length=2, null=True, verbose_name='political party'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(choices=[], default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[], default='00', max_length=2, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spjob',
            field=models.CharField(blank=True, choices=[], default='00', max_length=2, null=True, verbose_name='special job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[], default='10', max_length=2, null=True, verbose_name='employ status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag1',
            field=models.CharField(blank=True, choices=[], default='99', max_length=2, null=True, verbose_name='tag1 fzjr'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag2',
            field=models.CharField(blank=True, choices=[], default='9', max_length=2, null=True, verbose_name='tag2 dwld'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag3',
            field=models.CharField(blank=True, choices=[], default='00', max_length=2, null=True, verbose_name='tag3 dsjs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag4',
            field=models.CharField(blank=True, choices=[], default='0', max_length=2, null=True, verbose_name='tag4 byzk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ygxs',
            field=models.CharField(blank=True, choices=[], default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='expenseaccount',
            name='category',
            field=models.CharField(choices=[('HR', 'HR-DOMAIN'), ('OF', 'OFFICE-DOMAIN'), ('PU', 'PUBLIS-DOMAIN'), ('MU', 'MUNADOMAIN'), ('BU', 'BUSINESS'), ('OT', 'OTHER')], default='PU', max_length=4, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='extraparam',
            name='data_type',
            field=models.CharField(choices=[('CHAR', 'CHAR'), ('NUM', 'NUMBER'), ('DATE', 'DATE')], default='CHAR', max_length=6, verbose_name='data type'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='family title'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[], default='17', max_length=2, null=True, verbose_name='social status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tp',
            field=models.CharField(blank=True, choices=[], default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=2, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Supplier')], default='C', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to='project', verbose_name='blueprint'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business',
            field=models.FileField(blank=True, null=True, upload_to='project', verbose_name='business document'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='offer sheet', verbose_name='offer sheet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'C'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_type',
            field=models.CharField(blank=True, choices=[], default='00', max_length=2, null=True, verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[], default='00', max_length=2, null=True, verbose_name='status'),
        ),
    ]
