# Generated by Django 3.2.8 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='01', max_length=2, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(default='1', max_length=2, verbose_name='edu type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, default='CN', max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health',
            field=models.CharField(blank=True, default='1', max_length=2, null=True, verbose_name='health'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='literacy',
            field=models.CharField(blank=True, default='10', max_length=2, null=True, verbose_name='literacy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, default='99', max_length=2, null=True, verbose_name='major type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital',
            field=models.CharField(blank=True, default='10', max_length=2, null=True, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, default='01', max_length=2, null=True, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, default='13', max_length=2, null=True, verbose_name='political party'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, default='00', max_length=2, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spjob',
            field=models.CharField(blank=True, default='00', max_length=2, null=True, verbose_name='special job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, default='10', max_length=2, null=True, verbose_name='employ status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag1',
            field=models.CharField(blank=True, default='99', max_length=2, null=True, verbose_name='tag1 fzjr'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag2',
            field=models.CharField(blank=True, default='9', max_length=2, null=True, verbose_name='tag2 dwld'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag3',
            field=models.CharField(blank=True, default='00', max_length=10, null=True, verbose_name='tag3 dsjs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag4',
            field=models.CharField(blank=True, default='0', max_length=2, null=True, verbose_name='tag4 byzk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ygxs',
            field=models.CharField(blank=True, default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='family title'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, default='17', max_length=2, null=True, verbose_name='social status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tp',
            field=models.CharField(blank=True, default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_type',
            field=models.CharField(blank=True, default='00', max_length=2, null=True, verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='00', max_length=2, null=True, verbose_name='status'),
        ),
    ]
