# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='menu code')),
                ('name', models.CharField(max_length=40, verbose_name='menu name')),
                ('url', models.URLField(blank=True, max_length=80, null=True, verbose_name='menu url')),
                ('weight', models.IntegerField(blank=True, default=99, null=True, verbose_name='weight')),
                ('icon', models.CharField(blank=True, max_length=40, null=True, verbose_name='style class')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='module code')),
                ('name', models.CharField(max_length=40, verbose_name='module name')),
                ('url', models.URLField(blank=True, max_length=80, null=True, verbose_name='module url')),
                ('weight', models.IntegerField(blank=True, default=99, null=True, verbose_name='weight')),
                ('icon', models.CharField(blank=True, max_length=40, null=True, verbose_name='style class')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syscfg.Module', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'module',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='role code')),
                ('name', models.CharField(max_length=40, verbose_name='role name')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='description')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('menus', models.ManyToManyField(blank=True, to='syscfg.Menu', verbose_name='role menus')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syscfg.Role', verbose_name='parent')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='role users')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'role',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('name', models.CharField(max_length=40, verbose_name='site name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='site description')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='administrator')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Site',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syscfg.Module', verbose_name='module'),
        ),
    ]
