# Generated by Django 3.0.7 on 2020-06-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_auto_20200615_1024'),
        ('purchase', '0002_auto_20200615_1024'),
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinventory',
            name='attach',
            field=models.FileField(blank=True, help_text='参考FD0002模板文档', null=True, upload_to='inventory', verbose_name='attach'),
        ),
        migrations.AlterField(
            model_name='initialinventory',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('9', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='prop',
            field=models.CharField(choices=[('+', 'PLUS'), ('-', 'MINUS')], default='+', max_length=2, verbose_name='plus or minus property'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='po',
            field=models.ForeignKey(blank=True, limit_choices_to={'entry_status': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'QUALITY TESTING'), ('9', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='wareadjust',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='warereturn',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=2, verbose_name='status'),
        ),
    ]
