# Generated by Django 3.2.8 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='tax',
            field=models.CharField(default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('00', 'NEW'), ('01', 'IN PROGRESS'), ('04', 'DROP'), ('09', 'APPROVED'), ('99', 'ALREADY STOCK IN')], default='0', max_length=2, verbose_name='status'),
        ),
    ]
