# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ', '0001_initial'),
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee departure',
                'verbose_name_plural': 'employee departures',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_way', models.CharField(default=b'10', max_length=2, verbose_name='calculate way')),
                ('fixed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='fixed value')),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='base value')),
                ('org_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='org percent')),
                ('employee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='employee percent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'salary item',
                'verbose_name_plural': 'salary item',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='employee number')),
                ('name', models.CharField(max_length=120, verbose_name='employee name')),
                ('pinyin', models.CharField(blank=True, max_length=120, null=True, verbose_name='pinyin')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.CharField(default=b'1', max_length=2, verbose_name='gender')),
                ('idcard', models.CharField(max_length=20, verbose_name='id card')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='mail address')),
                ('zipcode', models.CharField(max_length=8, verbose_name='zipcode')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('rank', models.CharField(default=b'00', max_length=2, verbose_name='employee rank')),
                ('ygxs', models.CharField(blank=True, default=b'2', max_length=2, null=True, verbose_name='employ ygxs')),
                ('category', models.CharField(blank=True, default=b'21', max_length=2, null=True, verbose_name='employ category')),
                ('probation_months', models.CharField(default=b'3', max_length=2, verbose_name='probation months')),
                ('probation_begin', models.DateField(default=datetime.date.today, verbose_name='probation begin')),
                ('probation_end', models.DateField(blank=True, null=True, verbose_name='probation end')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='memo')),
                ('profile', models.FileField(blank=True, null=True, upload_to=b'hr profile', verbose_name='profile')),
                ('guider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Employee', verbose_name='guider')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Position', verbose_name='designate position')),
            ],
            options={
                'verbose_name': 'employee entry',
                'verbose_name_plural': 'employee entries',
                'permissions': (('modify_salary_item', 'modify salary item'),),
            },
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('classification', models.CharField(default=b'10', max_length=2, verbose_name='classification')),
                ('plus_or_minus', models.CharField(default=b'+', max_length=2, verbose_name='plus or minus')),
                ('required', models.BooleanField(default=0, verbose_name='is required')),
            ],
            options={
                'ordering': ('code',),
                'verbose_name': 'salary item',
                'verbose_name_plural': 'salary items',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee transfer',
                'verbose_name_plural': 'employee transfers',
            },
        ),
        migrations.AddField(
            model_name='employeesalaryitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Entry', verbose_name='employee entry'),
        ),
        migrations.AddField(
            model_name='employeesalaryitem',
            name='salary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.SalaryItem', verbose_name='salary item'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalaryitem',
            unique_together=set([('entry', 'salary_item')]),
        ),
    ]
