# Generated by Django 3.2.8 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryitem',
            name='calculate_way',
            field=models.CharField(default='10', max_length=2, verbose_name='calculate way'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='probation_months',
            field=models.CharField(default='3', max_length=2, verbose_name='probation months'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rank',
            field=models.CharField(default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ygxs',
            field=models.CharField(blank=True, default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='classification',
            field=models.CharField(default='10', max_length=2, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='plus_or_minus',
            field=models.CharField(default='+', max_length=2, verbose_name='plus or minus'),
        ),
    ]
