# Generated by Django 3.2.8 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='tax',
            field=models.CharField(default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax',
            field=models.CharField(default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_type',
            field=models.CharField(default='10', max_length=6, verbose_name='invoice type'),
        ),
    ]
