# Generated by Django 3.0.7 on 2020-06-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_auto_20200615_1024'),
        ('selfhelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='activity', verbose_name='attach'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='classification',
            field=models.CharField(blank=True, choices=[('T', 'Train'), ('M', 'Meeting'), ('G', 'Community')], default='M', max_length=2, null=True, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'tp': 20}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rank',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=2, null=True, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('I', 'IN PROGRESS'), ('A', 'APPROVED'), ('P', 'PAYED')], default='N', max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('I', 'IN PROGRESS'), ('A', 'APPROVED'), ('P', 'PAYED')], default='N', max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='attach',
            field=models.FileField(blank=True, help_text='工单附件，不导入明细。', null=True, upload_to='', verbose_name='attach'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='business_domain',
            field=models.CharField(choices=[], default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='classification',
            field=models.CharField(choices=[], default='D', max_length=4, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='detail',
            field=models.FileField(blank=True, help_text='您可导入需求明细，模板请参考文档FD0007', null=True, upload_to='', verbose_name='to be imported detail'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, choices=[], default='NEW', max_length=6, null=True, verbose_name='status'),
        ),
    ]
